### ISSUE TITLE
Add `neuron query --list-tags`

### ISSUE THREAD

**Issue by srid** [srid/neuron#110]
A way to retrieve the list of all tags used in a Zettelkasten.

CLI spec: `(--list-tags | --tag TAG | --uri)`

**Comment by srid** [comment]
As well as perhaps `--uri zquery://tags` (so that we can have a zettel show a list of links to tags as well).

**Comment by felko** [comment]
Since #115, a `--tag-tree` command might be helpful to allow editors plugins to implement some kind of "tag browsing" feature.

**Comment by srid** [comment]
Agreed. What would be the zquery URI equivalent? Here's what I think, at the moment:

* `zquery://tags` -- show a list of tags in the UI, linking to search.html?tag=foo
* `zquery://tags?tree` -- same, but render as a tree
  * Or, alternatively, `zquery://tags?root=/` -- same as before
  * Whereas `zquery://tags?root=math` would render only the math sub-tree

Then have CLI map to those queries.

**Comment by felko** [comment]
Do all the queries need to have a corresponding URI? I would prefer `zquery://tags` to display the tree in all cases, as it is easier to browse.

I like the `zquery://tags?root=math`. I would also allow globbing like `zquery://tags?glob=math/*` since it could happen that you want to display the tree only one level deep.

What would the output look like in the HTML? Will the matched tags be displayed in a tree without any zettels inside? If so, then some kind of `zquery://outline?root=math` might be useful as well. Here is an idea of how that would look like, assuming there are zettels tagged `math/algebra` and `math/calculus`:

```
# math
[.](zquery://search?tag=math)

## algebra
[.](zquery://search?tag=math/algebra)

## calculus
[.](zquery://search?tag=math/calculus)
```

That allows the creation of "dynamic outlines" which are automatically updated as new zettels are created under the `math` tag.

**Comment by srid** [comment]
It is good to have a 1-on-1 map to queries. I think of `neuron query --whatever` simply as an alias for using the full form `neuron query --uri`. Plus, it forces us to think how whatever querying we add to the CLI would impact the HTML view.

Alright, let's do tree by default, and go with `zquery://tags?filter=math` and `zquery://tags?filter=math/*` ("filter" is more appropriate naming here, and consistent with the tag-based filtering of `search?tag=...`).

> What would the output look like in the HTML? 

Tree of links to the tag search page.

> Will the matched tags be displayed in a tree without any zettels inside? 

Why would we show the zettels? The user is querying for tags only, not the zettels.

Your outline proposal should indeed be discussed in a different issue (and since you are querying for zettels effectively, it should be done in the zettel query search, but perhaps with a `groupBy` option i.e.: `zquery://search?tag=math/**&groupBy=tag`).

**Comment by srid** [comment]
`neuron query --uri zquery://tags` returns all tags (as tree), but if somebody really wants a list format, open a PR.
