### ISSUE TITLE
Display tags in the results of a zquery

### ISSUE THREAD

**Issue by srid** [srid/neuron#116]
With hierarchical tags (of #115) this becomes kind of useful. In a zquery list of zettels show the tag associated with zettel next to the link. 

Need to decide on the zquery URI spec for this. Might involve revamping the whole `LinkTheme` thingy.

**Comment by felko** [comment]
Here is an idea of link themes that could control how tags are displayed:
- `hide` (default): do not show tags
- `showTags`: show all tags regardless of the query that linked the zettel
- `showMatchingTags`: show the tags that caused each zettel to be matched by the query

In my personal zettelkasten I have a zettel that gathers all zettels that are tagged `todo/**`. That allows me to see in one place all zettels that I need to write or improve, for example I can tag a zettel `todo/expand-second-paragraph`. The `showMatchingTags` might be helpful here since I can see what I need to do, directly in the results of the query, without having all tags displayed.

**Comment by srid** [comment]
I think the feature behind `showMatchingTags` is useful, but the `LinkTheme` thing is not designed to my satisfaction. We have three link themes: default, simple and "withDate"; none of them take arguments from the URI (yet). Where would "showMatchingTags" would fit in?

**Comment by srid** [comment]
Closing in favour of #118
