### ISSUE TITLE
Add CLI interface for single-result queries

### ISSUE THREAD

**Issue by felko** [srid/neuron#142]
There is no interface in `neuron query` for queries like `Query_ZettelByID` (see `Neuron.Zettelkasten.Query` module), which return a single zettel with a given ID. In particular, there is no URI scheme that queries a single zettel, which would allow the use of `neuron query --uri`.

This will be solved with #59 anyway, but having a non-URI interface like `neuron query --id ID` might be useful too.

That will allow editors to get information about zettels from their IDs, like tags, title, etc... which might be useful for implementing features like <https://github.com/felko/neuron-mode/issues/16>.

**Comment by srid** [comment]
Before/during we do this, I'd like to change the structure of the resulting JSON (of all query types) a bit. 

For example, in place of returning zettels list JSON as `[{"id": ..., "title": ..., ...}]`, I'd like that to also include the query type itself, i.e.: `{"query": {"type": ZettelsByTag, "tagPaterns": [..]}, "results": [{"id" ...}]}`.

This is just for being explicit, so that clients can write predictable JSON parser without having to parse the input query themselves.

**Comment by srid** [comment]
![image](https://user-images.githubusercontent.com/3998/80429498-3f914100-88ba-11ea-9706-f378ec43b03b.png)
