### ISSUE TITLE
Make title optional

### ISSUE THREAD

**Issue by srid** [srid/neuron#181]
In the absence of the title, use the first few words of the first paragraph. Consequently, the entire metadata block becomes optional. And people can just start typing notes with nothing but their thoughts.

cf. https://lobste.rs/s/kydg6q/neuron_0_4_zettelkasten_note_management

> Titles for cards. These, to me, are an error and lead to ideas being discarded that have value in context. Often it’s much easier to have an idea in context and to write it down. Forcing titling of ideas leads to ideas being discarded that would otherwise (in context) be valuable.

**Comment by Nadrieril** [comment]
A complete proposal that includes https://github.com/srid/neuron/issues/196 would be:
- if there is a `title` entry in the metadata, use that
- otherwise, if there is a heading (`# Some title`), use the first one
- otherwise, use the first few words of the first paragraph

The heading is something that makes sense at the level of the Pandoc AST and thus should work with multiple input formats.
