### ISSUE TITLE
Feature Request: Embed Zettels into other Zettels

### ISSUE THREAD

**Issue by michelk** [srid/neuron#184]
One idea, one zettel, right?

Additional to just link to other zettels, it would be nice to be able to embed the contents of one zettel into another one, where the `title` becomes a `heading`. 

Syntax proposal similar to images: `!<abcdef>`

E.g.

zettel `1234.md`:
```markdown
---
title: Test A
--- 
bla bla bla
```

Then  

```markdown
---
title: Test B
---

!<1234>

# Section 1

!<1234>

```

Generates 

```markdown
---
title: Test B
---

# Test A
bla bla bla

# Section 1

## Test A
bla bla bla

```

**Comment by srid** [comment]
@michelk Which (real world) use case prompted this?

**Comment by michelk** [comment]
With this, it would be  possible to compile multiple ideas into one document, which is sometimes easier to read. Or compile a technical report from single pieces.

**Comment by jaygray0919** [comment]
IMHO the proposal is not a good idea. We come from an `RDF` world where a single fact is expressed as a subject, predicate and object (?s ?p ?o in SPARQL syntax). Two or more facts are related based on sharing an `s` `p` and/or `o`. A sentence or a paragraph is constructed from those facts. `Embedding` is not supported (allowed) in RDF because it would defeat the `fact and linking` structure. While information in a zettel is much more elaborate than an RDF assertion/axiom, the structure of a zettel should be semantically equivalent to an RDF axiom.
Of course, with `Neuron`, we only know that there are relationships among zettels. We don't know the names of those relationships - we don't know the significance of the relationships.
But that's OK, because communication is messy, and zettels help formalize messy ideas.
Once the facts (zettels) are clearly defined, and zettel relationships are visible in the index, we can work to transform messy ideas into more formalized systems (code).
IOHO it's a bad idea to hide/obscure/overload facts with techniques like embedding one idea in another.

**Comment by srid** [comment]
> With this, it would be possible to compile multiple ideas into one document, which is sometimes easier to read. Or compile a technical report from single pieces.

There are ways to do this, for example using the `neuron query` command and making use of tags. You could try this workflow:

* Add a tag, say `report`, to the individual zettels
* With [jq](https://stedolan.github.io/jq/) installed, run `neuron query -t report | jq -r .result[].path | xargs cat`
* [Copy](https://stackoverflow.com/questions/5130968/how-can-i-copy-the-output-of-a-command-directly-into-my-clipboard) the output of that command.
* Paste it in a new Markdown document (doesn't have to be in the zettelkasten).

Compiling reports and such is a concern orthogonal to writing and developing one's Zettelkasten (which is about atomic notes connected to one another), so I don't think this should be done in neuron.

**Comment by michelk** [comment]
I agree. This should be solved with external tooling.

**Comment by RoyiAvital** [comment]
This would be great to have.

I would propose the following syntax: `![[ZettleName.md]]` / `![[[ZettleName.md]]]`.

I would go even farther. Using `#` one could add hierarchy.
So something like: `!![[ZettleName.md]]` would mean headers in the embedded Zettel will inherit the headings they were embedded to.

So, Zettel `1234.md`:

```
---
title: Test A
--- 
bla bla bla

```

Then

```
---
title: Test B
---

# Section 1
![[1234]]

# Section 2

!![[1234]]
```

Will yield:

```
---
title: Test B
---

# Section 1

# Test A
bla bla bla

# Section 2

## Test A
bla bla bla
```
