### ISSUE TITLE
Surrounding context in backlinks

### ISSUE THREAD

**Issue by srid** [srid/neuron#190]
The "surrounding context" of a link or a tag is the text surrounding it. 

* When showing backlinks, we should as well display (in some manner) this surrounding context.
* When showing a list of zettels by tag, we should show the surrounding context of the inline tag (requires #189)

For example, if a zettel links to two other zettels:

```
Anger throws one off the learning [[er3ksi33h]]. 

Feeling of rushing/impatience dislodges us from a 
state of flow, which is essential for [[h4hd8hekk]]
```

In the zettel `[[er3ksi33h]]` (titled Mindset), the link to this zettel should also show the surrounding context which is "Anger throws one off the learning \<Mindset>. " Same for the second link.

Likewise, for if a zettel uses a tag:

```
Gaslighting is enabled by the victim's #psychology/cognitive-distortion
without which the victimizer is rendered powerless to influence their victim.
```

Then when displaying its link in a zettel that queries for the tag, we should display (perhaps as hover text) its surrounding text.

**Comment by felko** [comment]
This could be done using something like "hovercards", instead of showing the context in the backlinks section. Example:
![image](https://user-images.githubusercontent.com/9366592/82061855-89a36080-96c9-11ea-9592-ea3f7d101b68.png)

**Comment by srid** [comment]
Good idea. And yes, that's the kind of UI I'm leaning towards. <sup>A larger goal here is to continue to keep the UI lightweight and simple.</sup>

**Comment by leira** [comment]
Rather than hover cards, I do see the value of a plain backlist of contexts. It is just like Roam Research's backlists, which makes even a empty with just backlinks useful. This is not the best example, but this is the picture I can find: ![Roam Research](https://i2.wp.com/anthrodendum.org/wp-content/uploads/2020/05/Screen-Shot-2020-05-03-at-8.39.53-PM.png)

One use case I really like to see is, I use Neuron for project pages and work journals. I want to keep everything I do on the journal page, but I also want to aggregate all the relevant journal entries to the project page. With surrounding context, it is very easy to do. Any mention of the project page will be aggregated with context in the project page.

With surrounding context, it will enables a lot of very interesting use cases.

**Comment by bulbousBullfrog** [comment]
I'm also interested in being able to 'label' links between notes, for example to label with a reason as explained in #185 . While I do like the idea of surrounding text as context, I was actually wondering if it would be possible to have a note itself be the link label between two notes notes.
For example the following linked three notes:

```<JournalYYYYMMDD>    ⤚⤞   <Zen Meditation>    ⤚⤞    <Meditation Methods>```

could be labeled like this

```<JournalYYYYMMDD>  ⤚<Reasons for Meditation>⤞   <Zen Meditation>    ⤚"is a"⤞    <Meditation Methods>```

By being able to use notes as link labels, there is the potential to have additional information in the structure for free. For example, look what happens when we have two note-links:

```<JournalYYYYMMDD>   ⤚<Reasons for Meditation>⤞   <Zen Meditation>  ⤚<Preferred Methods>⤞  <Meditation Methods>```

we have the set of 3 original notes:
`<JournalYYYYMMDD>, <Zen Meditation>, <Meditation Methods>`

but then we also have a new set of note-links that themselves are a Folgezettel:
`<Reasons for Meditation> ⤚⤞ <Preferred Methods>` 

This connection may have never been made manually, but it 'falls out' of the structure. 

Brainstorming like this shows it could have benefits for future features. After all a text label can just be seen as an empty note with only a title.  

Note: If viewing a Zettelkasten as a category, this may be related to the [Arrow Category](https://ncatlab.org/nlab/show/arrow+category)

**Comment by srid** [comment]
@bulbousBullfrog Link labels can be implemented as a plugin (we don't have a plugin architecture yet; it is in roadmap), without baking it into the core of neuron. 

commonmark's attributes extension can be used to extend Markdown, so you can do something like: `[[meditation-method]]{.label=is-a}`.

@leira Agreed.
