### ISSUE TITLE
column view for Zettel searches

### ISSUE THREAD

**Issue by smunix** [srid/neuron#225]
It is visually better to present a long list of Zettel searches as columns. See examples below:
### srid.ca
![srid ca-0](https://user-images.githubusercontent.com/540621/84272397-581c8a00-aafb-11ea-9bf9-914f6db3ada4.jpeg)
![srid ca-1](https://user-images.githubusercontent.com/540621/84272399-58b52080-aafb-11ea-9340-e94a99044276.jpeg)
### smunix.gitlab.io
![smunix-0](https://user-images.githubusercontent.com/540621/84272468-6f5b7780-aafb-11ea-8da2-0d6064a66008.jpeg)
![smunix-1](https://user-images.githubusercontent.com/540621/84272469-6ff40e00-aafb-11ea-9569-c60f400dee04.jpeg)

Users can opt-in this feature by adding a query parameter, "columns", that'd take the number of columns as its input. I can submit a PR if this is something you'd be interested to see.

**Comment by smunix** [comment]
Thinking about it, a product type is also desirable. I have this other portal where I use a combination of GroupByTag and Columns both. What's your feeling for this?

![smunix-2](https://user-images.githubusercontent.com/540621/84691791-b9d15f80-af12-11ea-8fe6-e20bab863fd2.jpeg)

**Comment by srid** [comment]
What's the original goal that prompted this? I'm asking because if we knew the original desire/goal, then a better solution can be thought of.

I'm also wondering why you opted for `<table>` instead of [stackable grids](https://fomantic-ui.com/collections/grid.html#stackable). With later we could render the results unconditionally in stackable grids, making the column count customizable (on mobile devices it will vary for accessibility). If you put result groups in a grid column, that should more or less achieve your goal, I'd think. And now it would just be a product type. I wonder how it would look like in practice ...

**Comment by smunix** [comment]
The original desire was for me to avoid a single long list of zettels, while there was free space on the right side of the page. I thought laying out the zettel list to cover more of the page would yield better visuals.

As to why <table> was chosen over stackage grids, there's no reason other than it's my first Web programming code that I'm writing. I've never known anything else other than tables to lay things out in a "tabular" fashion.

Thank you for pointing to [stackable grids](https://fomantic-ui.com/collections/grid.html#stackable), they look like a better fit. Let me have another round on this with stackable grids.

**Comment by smunix** [comment]
@srid this is completed now, help review please

**Comment by srid** [comment]
Closing per https://neuron.zettel.page/next ... to further discuss this idea, [post in Emanote repo](https://github.com/srid/emanote/issues/new/choose).

**Comment by srid** [comment]
But see https://github.com/srid/emanote/discussions/106 for a more general idea
