### ISSUE TITLE
Full themes support

### ISSUE THREAD

**Issue by srid** [srid/neuron#253]
What we have right now is the ability to override color schemes. It would be nice to also be able to override HTML layout and CSS styles.

Since neuron uses reflex-dom for HTML and clay for CSS, a theme could simply be a Haskell package with an interface. Not yet sure how exactly it would all be hooked up. 

Switching themes, and developing on them, should work in the `bin/run` workflow. How the user can configure them is an open-ended question at the moment.

See https://github.com/srid/neuron/labels/case-for-themes

**Comment by srid** [comment]
Custom properties would come in handy here. For example:

```markdown
---
tags: [ foo ]
custom:
  comments: true 
---
```

Then, in the custom theme one could do `Map.lookup "comments"` and include the comments of #270 only if this property is set in the zettel.

**Comment by TheMatten** [comment]
Related to this, dark version of current theme would be great:
![image](https://user-images.githubusercontent.com/21198836/87950280-628d5480-caa7-11ea-9e12-30672105a52f.png)
*(screenshot done with Dark Reader extension enabled)*

**Comment by srid** [comment]
My understanding here is that fully customizable themes support is a hard problem if HTML is defined in Haskell (reflex-dom). However, as a middle-ground, we could enhance the default theme to be flexible enough (with toggleable sidebars, dark theme, etc.)

**Comment by jared-w** [comment]
One way to support fully customizable themes would be to add in support for something like handlebars, along with a theme structure (`static/templates/{index,zettel,search}.html`, for example) and fill in certain variables like `siteTitle`, `title`, `content`, etc.

Unfortunately, this approach would end up essentially duplicating the site rendering code for very little gain.

Alternatively, since the existing HTML is already quite semantic and well tagged with classes, simply giving the options to omit the generated CSS and/or include any css files found in `static/css` in the bottom of the header would go a long way to allowing everything from simple small overrides to full re-themes.

**Comment by srid** [comment]
FWIW, I'm now open to switching from reflex-dom to using plain .html templates. If somebody wants to take a stab at it ...

We should decide on a template language first. It should support looping construct in some form, so that query results can be rendered.

**Comment by samwalls** [comment]
Is this of any use for templating in this case? https://github.com/snapframework/heist

**Comment by srid** [comment]
`heist` could work even if a bit weird looking. Ideally I'd go with something user friendly and popular like shopify's `liquid` - but Haskell doesn't really have a good choice of tempting languages.

**Comment by jared-w** [comment]
@srid the idea of multiple templates is that there are multiple different pages being rendered currently.

- home page
- impulse
- (upcoming search page)
- zettel page [currently the same as the home page but, in theory, doesn't have to be]

I'd imagine something along the lines of `foo.md -> [ foo.html if existing or template.html otherwise ] -> foo.html`.

Practically, I don't think many people will customize all of those things, but I know that I personally usually make my home page fairly different than the other pages when possible, and it'd be nice to do that.

---

As far as templating languages go, I tend to go for popularity over ease of use; they're all quite similar, so picking a popular one means people can find examples easier. Handlebars fits that fairly well and the existing handlebar haskell library isn't bad; but liquid, ginger, etc., all seem fairly interchangeable.

**Comment by srid** [comment]
An advantage with Heist is that you can specify how to render Pandoc AST nodes,

```xml

        <ema:note:pandoc>
          <PandocLink class="text-${theme}-600">
            <Internal class="font-bold hover:bg-${theme}-50" />
            <External class="hover:underline" target="_blank" rel="noopener" />
          </PandocLink>
          <Para class="my-2" />
          <CodeBlock class="py-0.5 text-sm" />
          <OrderedList class="ml-4 space-y-1 list-decimal list-inside" />
          <BulletList class="ml-4 space-y-1 list-decimal list-inside" />
          <Header>
            <h1 class="pb-2 mt-2 mb-2 text-6xl text-center" />
            <h2 class="mt-4 mb-2 text-5xl text-gray-700" />
            <h3 class="mt-4 mb-2 text-4xl text-gray-700" />
            <h4 class="mt-4 mb-2 text-3xl text-gray-700" />
            <h5 class="mt-4 mb-2 text-2xl text-gray-700" />
            <h6 class="mt-4 mb-2 text-xl text-gray-700" />
          </Header>
        </ema:note:pandoc>
```

Or how to render sidebar tree (I don't think is possible normal templates, unless you pass in raw HTML - but that cannot be styled),

```xml
      <div class="hidden overflow-x-auto md:mr-4 md:block md:col-span-3 md:sticky md:top-0 md:h-screen">
        <div class="pt-1 pb-2 rounded bg-${theme}-50">
          <ema:route-tree>
            <sub-tree class="pl-2" />
            <item-parent class="my-2" />
            <item-terminal class="my-2 text-gray-600" />
            <link-active class="font-bold text-${theme}-600 hover:text-black" />
            <link-inactive class="hover:text-black" />
            <!-- TODO: styling based on document meta, example: -->
            <link-doc-meta name="tags" contains="pinned" class="bg-pink-100" />
          </ema:route-tree>
        </div>
      </div>
```

**Comment by srid** [comment]
Full theming is available in Emanote.

Closing per https://neuron.zettel.page/next ... to further discuss this idea, [post in Emanote repo](https://github.com/srid/emanote/issues/new/choose).
