### ISSUE TITLE
Add binary artifacts to releases

### ISSUE THREAD

**Issue by TheMatten** [srid/neuron#292]
I would like download linux bundles of `neuron` in CI outside of Github (https://funprog.zulipchat.com/#narrow/stream/231929-Neuron/topic/Gitlab.20Pages/near/204132793), but Github API seems to require authentification for that - would it be possible to add artifacts from neuron's CI into (publicly available) releases?

**Comment by srid** [comment]
Some notes on the artifacts thing here: #260

I don't want to have to *manally* upload a bundle to the release area, because that can easily become out of date (and I don't want to spend much time updating it manually every time). What I'd like to do is automate the upload-to-release thing. Perhaps a single "nightly" release that gets updated with the latest master's nix bundle?

**Comment by TheMatten** [comment]
Should be doable combining these two actions:
- https://github.com/marketplace/actions/create-a-release
- https://github.com/marketplace/actions/upload-a-release-asset

**Comment by srid** [comment]
Added in #295

Available at https://github.com/srid/neuron/releases/tag/nightly

Will close after updating docs.
