### ISSUE TITLE
[DISCUSSION] Possible support for [[ link ]]-formatted links?

### ISSUE THREAD

**Issue by vcavallo** [srid/neuron#310]
I love neuron and its web features.
I also love wikis. Zettelkasten and wikis go together really nicely. `< link >` and `[[ link ]]` don't play nicely together, but the latter is often preferred in wiki managers (like vimwiki). https://github.com/michal-h21/vim-zettel nearly provides all the editor features I'd want (while neuron provides all the web features I'd want) - **the biggest (and maybe sole) stumbling block is that neuron doesn't work with `[[ ]]` links**.

Any chance neuron can soften-up about the format for links? Or perhaps provide this as an option?

**Comment by vcavallo** [comment]
My earlier searches failed me, apparently. I've just now found https://github.com/srid/neuron/issues/241 and see that this isn't recommended/supported for various reasons. 

I may still continue to use it with my fingers crossed :)

**Comment by srid** [comment]
Let me know how wiki-style links work out for you. It is not "officially recommended" because I'm waiting for feedback from varied users in regards to how well the various link types of neuron (including "z:zettesl?tag=.." style links) appear in other apps (Zettlr for example doesn't recognize "[[foo?cf]]" style links, i.e., with query in URI; and I'm pretty sure it doesn't recognize "[[z:zettels?tag=..]]").
