### ISSUE TITLE
Flexible links

### ISSUE THREAD

**Issue by srid** [srid/neuron#312]
**Proposal**

I propose the following linking syntax (retaining the underlying link URI):

```markdown
This is current style, and will continue to be supported: <foo>

Proposed default: [[foo]]

Flexible link, that allows setting inner text: [[foo | the foo note]].
```

This does a couple of things:

1. Makes the already supported `[[..]]` style links the *default*. 
2. Supports overriding the link text, as discussed in #306 

Advance linking syntax would look the same, except for the change in the 'wrapper' syntax:

```markdown

Current: 
- <z:zettels?tag=haskell>
- <foo?cf>

Proposed: 
- [[z:zettels?tag=haskell]]
- [[foo?cf]] or [[foo?cf | a foo note]]
```

Let's use this opportunity to also support regular Markdown links:

```markdown
Plain markdown links: 
- [a foo note](foo.md)
- [a foo note](z:/foo)
```

Something to think about: 
- how would these links look and behave in other Zettelkasten apps (emacs, vimwiki, Obsidian #229, Zettlr, ..)? Do we care? @vcavallo @felko @SquareBottle @EyebrowHairs
- How should links with user-defined inner text render stylistically?

---

### Final Proposal and Progress

- [x] Use `[[..]]` and `[[[...]]]` instead of `<..>` #351
- [ ] Allow overriding link text in wikilinks, eg: `[[ foo | a foo note ]]`
- [x] Regular Markdown links: `[a foo note](foo.md)`

**Comment by srid** [comment]
Oops, forgot to add one more thing:

```markdown
Plain markdown links: 
- [a foo note](foo.md)
- [a foo note](z:/foo)
```

**Comment by vcavallo** [comment]
As far as I can tell so far, unfortunately a lot of these still won't work with _vimwiki_ because it will assume that the bit within the `()` is a _filename_ and it will fail upon adding any query parameters or anything else.

This proposal will still be an improvement, though, as far as rendering the markup on the web.

**Comment by EyebrowHairs** [comment]
Just reporting my test with piped links on Zettlr. It's not an integrated thing, but it kind of works because Zettlr basically just does a search for a match and shows you the relevant matches. Although now I'm testing it using different title words and the search is too broad to find the right match...so the title needs to have at least one matching word with the actual note. Similar with the advanced link syntax, it performs a search, but you would need to delete the query part (?cf) so it can find a match. You could technically still use piped links though, because you can delete anything past the ID if needed to find an exact match. But it's also a bit cumbersome...

Otherwise I might just use MD links (using the filename rather than ID) because that actually works really well on Zettlr. Not sure how advanced linking syntax would work with that though. 

Stylistically I feel that it should be the same as a regular note link? If you're talking about how it appears on the web, that is.

**Comment by Nadrieril** [comment]
I like this!
Zettlr, Foam and TiddlyWiki use `[[foo]]` links too. TiddlyWiki also supports `[[foo|text]]`. Vimwiki seems to support it too? Anyways those two don't use markdown so it doesn't matter too much. Obsidian just doesn't support id-based linking. 

I'd prefer we used a more wiki-like syntax for special links. Here are three possibilities:
- we could borrow wikipedia's syntax for special links: `[[:Category:Help]]`. For example `[[:zettels:tag=haskell]]`.
- Wikipedia also has magic links like `{{ISBN|0-7475-3269-9}}` (see [here](https://en.wikipedia.org/wiki/Template:ISBN)). We could write `{{zettels|tag=haskell}}`.
- Another option is what TiddlyWiki does: they use e.g. `[backlinks[]]` to display backlinks. We could write `[zettels[tag=haskell]]`.

Those syntaxes can easily be extended to support inter-repo links, which we might want one day: `[[other-zk:foo]]`, `[[other-zk:zettels:tag=haskell]]`, `{{other-zk:zettels|tag=haskell}}`, `[other-zk:zettels[tag=haskell]]`.

I'm not sure what to do about the `?cf` links. Maybe `[[:cf:foo]]`?

**Comment by Coda-Coda** [comment]
I for one would appreciate the ability to have links of the form \[A note or description\]\(filename.md\) as my current Zettelkasten is in this format. Also I find this format very portable as pretty much any markdown editor supports the format (on PC and on mobile).

It would be awesome to be able to use Neuron without having to sacrifice portability due to the Neuron link format and it would help with future-proofing too.

Seems like an awesome project! I hope to be able to try it out on my own Zettelkasten 🙂

**Comment by Coda-Coda** [comment]
I have realised that it's not too difficult to write a script to switch all Zettels back and forth between `[A note or description](title.md)` and `[[title]] _(_ A note or description _)_` . So much as I would still like the ability to support traditional markdown links, at least I can already relatively easily use Neuron - and it seems really cool!

**Comment by srid** [comment]
@Nadrieril I like the Wikipedia magic links (aren't they called templates?). Something like `{{zettels|tag=haskell}}` does seem much simpler to type than URIs.

**Some thoughts on cf links**

In retrospect I should have made `cf` the default kind of links, with folgezettel links (one that appears in uplink tree) being marked explicitly, with say `?branch`. I think implementing this proposal gives us the opportunity to do this:

* `<foo>` becomes, say, `[[foo?branch]]`
* `<foo?cf>` becomes `[[foo]]`.

In the Wiki-style proposal, `[[foo?branch]]` doesn't look very good, so the question becomes: how do we flag the link type (such as branching links)? More generally, how can we specify "link labels" as proposed in https://github.com/srid/neuron/issues/190#issuecomment-669747790 ?

**Comment by vcavallo** [comment]
No comment on the rest at the moment, but I wanted to chime in and say I
totally agree about the default cf links.
-- 
Vinney Cavallo
Founder/Lead Developer, exnil.io

**Comment by srid** [comment]
> In the Wiki-style proposal, `[[foo?branch]]` doesn't look very good, so the question becomes: how do we flag the link type (such as branching links)? 

Use triple brackets to denote folgezettel links, eg: `[[[foo]]]`. This assumes that other Zettelkasten apps will still treat it as a link (albeit with superfluous `[...]` brackets)

**Comment by EyebrowHairs** [comment]
> Use triple brackets to denote folgezettel links, eg: `[[[foo]]]`. This assumes that other Zettelkasten apps will still treat it as a link (albeit with superfluous `[...]` brackets); it is in fact true for Zettlr.

Seems like an elegant solution! 

I am actually leaning more towards MD-style links now `[title](filename.md)`, simply because it hides the actual filename  while giving you the option to title it whatever you want, and because it works on Zettlr :D

Are there any cons anyone can see with that? I'm not sure how compatible it will be with other editors, and it still doesn't help with the cf problem...

**Comment by hoschi** [comment]
The down side of MD-style links is that you need to give it the title yourself. When you change the title of a zettel you would need to update all links and change all files.
With Neuron and the LSP you get all time up to date titles without work for yourself. I would like a way to give it an optional "titel" for links in sentences.
MD-styles are good for the latter case, but should not be the only/default way of linking, in my opinion.

**Comment by vcavallo** [comment]
This is great! Inter-op is already improved now with other wiki-like tools - and the `[[how-to-link | link]]` feature will only make this even better :)

Thanks!

**Comment by srid** [comment]
Regular markdown links (`[link](how-to-link.md)`) are now supported in `master`. They are treated as "cf" links.

---

Have we finalized on the `[[ foo | a foo note ]]` syntax? How does it work with other Zettelkasten apps?

**Comment by vcavallo** [comment]
@srid Does this mean that markdown links (with alt titles, as you exemplified above) _cannot_ be branching links?

**Comment by srid** [comment]
@vcavallo Not sure what you mean by "alt titles". If you define a link like this `[link](how-to-link.md)` - then the link to `how-to-link` zettel will be a `cf` link. In order to make that a folgezettel, you will have to switch to using wiki-style link, i.e., `[[[how-to-link]]]` or `[[[how-to-link | link]]]`.

**Comment by vcavallo** [comment]
Yep, that's exactly what I mean @srid. But do I have it right that the `[[[how-to-link | Link Title]]]` isn't ready yet? (meaning non-cf, branching links aren't yet possible with link text that differ from the note title).

**Comment by srid** [comment]
That's right. [That's what is left to do](https://github.com/srid/neuron/issues/312#issuecomment-683882567) for this issue -- see the checklist in issue description further above -- and I'd like to hear from folks using other Zettelkasten apps on the syntax proposed for it before it gets added to neuron.

**Comment by srid** [comment]
Moving what's left to #373
