### ISSUE TITLE
Determine smarter default value for `--zettelkasten-dir`, e.g. when `neuron.dhall` is in the current directory

### ISSUE THREAD

**Issue by peti** [srid/neuron#332]
I'm running neuron inside of my zettelkasten directory and there's even a `neuron.dhall` file that signifies the fact that it's a neuron-managed zettelkasten, but for some reason neuron won't notice that `.` is the right place to use for `-d`:

~~~
~/src/zettelkasten $ neuron query
neuron: user error (Zettelkasten directory /home/simons/zettelkasten does not exist.)
~~~

Instead, I have to run `neuron -d $PWD query`. That seems a little akward.

**Comment by srid** [comment]
Dup of #161

**Comment by peti** [comment]
It appears that #161 is dead in the water, though? The ticket is a collection of vague ideas, none of which is terribly actionable.

**Comment by srid** [comment]
There is a concrete proposal hidden in the comments.  The one by @maralorn basically, with the symlink part replaced by `path` in neuron.dhall. What's left is to write a RFC -- either as a comment or in a PR (better), and then implement it. 

I'd be happy if anyone is interested in taking this up; otherwise I'll get to it on my own pace. It definitely is a good idea, and one that should be done before version 1.0.
