### ISSUE TITLE
Loosely connected clusters

### ISSUE THREAD

**Issue by srid** [srid/neuron#349]
Right now the z-index displays totally disconnected clusters. But in practice, this is less useful. 

Consider [srid.ca's z-index](https://www.srid.ca/z-index.html), which has both "Life" and "Software" groups under the same cluster. They are more or less two separate clusters ... yet, because the Neuron zettel (under "Software") links to the "Use Zettelkasten for personal reflection" zettel (also linked under "Life"), neuron treats them as one cluster. This is not very useful.

![image](https://user-images.githubusercontent.com/3998/90544682-7cc55b80-e155-11ea-9aa1-e2c987608727.png)

The z-index should detect clusters, discarding "loose connections" like these.

What graph algorithms exist to do this?

**Comment by pbronez** [comment]
This is related to community detection in social networks. See [Community Structure on Wikipedia](https://en.wikipedia.org/wiki/Community_structure#Algorithms_for_finding_communities) for some details. [Girvan Newman](https://en.wikipedia.org/wiki/Girvan%E2%80%93Newman_algorithm) might work well for this use case, because it basically prunes away those "loose connections." I'm not aware of a Haskel implementation, but [SNAP has one in cpp](https://github.com/snap-stanford/snap/tree/cd3fb967c29049d9ff29063a2ae4115731638955/examples/community).

**Comment by srid** [comment]
Closing per https://neuron.zettel.page/next 

Maybe related: https://github.com/srid/neuron/issues/589
