### ISSUE TITLE
How to support generated static content?

### ISSUE THREAD

**Issue by peti** [srid/neuron#364]
I have plenty of notes that use graphics to illustrate their ideas and usually those graphics are generated programmatically, e.g. with Asymptote, Graphviz, or even LaTeX. Now, I realize that I can put those graphics into the `static/` directory to make Neuron copy them into the output directory verbatim. However, I wonder whether there is a way to make Neuron actually *generate* that static content from the appropriate source files? Neuron is based on Rib, which in turn uses Shake, so my intuition says that it should be possible to register some kind of shake rules that drive this generation process. I would probably need to write my own customized `neuron` executable to get that done, but I wouldn't mind that. Neuron seems to offer most of its functionality in the form of a re-usable library, right?

What do you think about this use-case? Is there an easy way to accomplish what I'm trying to do?

**Comment by srid** [comment]
@peti Okay, so, there are two ideas here:

1. Generate HTML from individual parts of the markdown file, eg: turning code snippets into rendered graphics. See https://github.com/srid/neuron/issues/228#issuecomment-670290253 ... I proposed that this can be done by supporting arbitrary Pandoc filters. See #363
1. Generate static files from other static files.

Both are about *dynamically generating* content for publishing that is not already available in the zettelkasten directory - but 2 deals with files, whereas 1 is about transforming the Pandoc document internally used by neuron.

Idea 2 is certainly interesting - but should this be in scope for a notes system? Even assuming it does, how would it be done?

Idea 1 on the other hand, I think, can certainly be in scope for neuron, because it is about transforming the Pandoc document arbitrarily so as to customize what gets rendered in the publish site - something you can't easily do outside of neuron without resorting to hacks as @b0o tried out in that link above.

**Comment by srid** [comment]
Closing in favour of #363, and it is not clear whether the specific use case is in scope for neuron (an equivalent of `Makefile` can be written and run outside of neuron?).
