### ISSUE TITLE
`neuron search -e` can't open files with blanks in filename

### ISSUE THREAD

**Issue by LATBauerdick** [srid/neuron#435]
at least not if `$EDITOR` is set to `nvim`. It looks like that the file name returned from fzf needs to escape the blank characters. 

e.g. if the search result returns the file name `one two.md`, the editor opens two files, with the filenames of `one` and `two.md`.

**Comment by srid** [comment]
I think this is because we are piping the filename output *unquoted* to the editor: https://github.com/srid/neuron/blob/a33ccad0b84bef9dc1c06ccd913f0e5d4724881c/neuron/src/app/Neuron/CLI/Search.hs#L36-L37

Changing the above to use `xargs` [as indicated here](https://unix.stackexchange.com/a/537160/14042) might be one fix.

**Comment by srid** [comment]
This is working in current `master` (probably due to #445?), so I'll close.
