### ISSUE TITLE
Raw HTML is not interpreted as one

### ISSUE THREAD

**Issue by flyinggrizzly** [srid/neuron#437]
Inserting the following HTML into a note:

```markdown
<!-- inline to prevent possible interpretation of indentation as code block -->
<video><source src='./static/otaku-builder-sdcs-unicorn-destroy-mode.mp4' type='video/mp4' /></video>
```
results in the following in the generated page:

![image](https://user-images.githubusercontent.com/10967676/96245491-46faf280-0f9f-11eb-842a-42a4ca425974.png)

```html
<p>
  <a href="video">video</a>
  <span class="ui left pointing red basic label">links to non-existant zettel: video</span>
  <source src="./static/otaku-builder-sdcs-unicorn-destroy-mode.mp4" type="video/mp4">
  <a href="/video">/video</a>
</p>
```

I can embed the video with an iframe, but I prefer to actually save files that are potentially ephemeral (like Youtube videos).

**Comment by srid** [comment]
Raw HTML needs to be wrapped in code-blocks, in order to disambiguate the meaning of "<video>" (how can neuron tell it is not a link to `video.md`? Try:

```markdown
    ``` {=html}
    <video><source src='./static/otaku-builder-sdcs-unicorn-destroy-mode.mp4' type='video/mp4' /></video>
    ```
```

Example: https://raw.githubusercontent.com/srid/guide.cerveau.app/master/index.md

**Comment by srid** [comment]
Documentation on this custom syntax: https://github.com/jgm/commonmark-hs/blob/master/commonmark-extensions/test/raw_attribute.md

**Comment by flyinggrizzly** [comment]
Yup, that works. I’m also now seeing the autolink footnote in the Neuron guide, which I’m assuming why Neuron has the issue with (some, but not all?) HTML elements. 

Given my expectation that valid HTML is valid markdown, this definitely took me by surprise.

(I’m trying to figure out how to phrase this that’s not just entitled user, but I’m sorry if I miss the mark)—would it be worth considering deprecating the auto link behavior in Neuron now that wiki links are recommended, so that there isn’t the issue with HTML in MD? Not fully supporting HTML in the markdown is definitely a surprise for people who are used to MD, especially anyone who uses it with existing static site generators. 

This would make migrating potentially easier for folks coming from pure MD environments. 

But I’m also very aware that it would leave existing Neuron users with a problem...

If that breaking change isn’t something you want to do, maybe something about this in the Zettel Markdown docs at least would help others who run into the same issue?

**Comment by srid** [comment]
`<..>` style links are already considered deprecated. Dropping support for them can be considered, as long as there is an automated migration path (a reliable script that rewrites links, for instance) for existing notebooks. Also note that internally neuron converts `[[..]]` links to `<..>` links; so that will have to be dealt with as well (which should hopefully be fairly simple, by full expanding the URIs, eg: `[[foo]]` -> `<z:link/foo>`, so as to disambiguate from HTML tags). 

Meanwhile we can indeed document all this. A new page, under https://neuron.zettel.page/markdown.html, can be added describing how to use raw HTML. PR welcome for that!
