### ISSUE TITLE
Backlinks panel takes too much space

### ISSUE THREAD

**Issue by srid** [srid/neuron#456]
This could use the eyes of someone with CSS skills. The position of tag labels in backlinks panel is not right, when it should ideally be appearing floated right (in the same row). Can this be done? See screenshot: 

![image](https://user-images.githubusercontent.com/3998/98153949-f8f05500-1ea1-11eb-806d-e8bfe5663d31.png)

From https://zettel.lost-frequencies.eu/f7f07adf.html

**Comment by yeldiRium** [comment]
Is this still relevant with the new way that tags are rendered? Since they are now below the backlinks and stack horizontally, there is no need to have them float upwards anymore. (I can't find the commit that introduced this change.)

![image](https://user-images.githubusercontent.com/11889637/100927327-0884ad00-34e5-11eb-9d2e-9dede2631854.png)

**Comment by srid** [comment]
Oh yea, this should be considered fixed. It was done as part of #468
