### ISSUE TITLE
Parsing fails on non-RFC3986 compliant urls

### ISSUE THREAD

**Issue by luc-tielen** [srid/neuron#54]
With the following zettel:
```markdown
---
title: Title here
---

- [Some link](http://example.com/articles?include=author&fields[articles]=title)
```

I get this error:

```
[Rib] Unhandled exception when building <unknown>: Error when running Shake build system:
  at action, called at src/Development/Shake/Forward.hs:123:5 in shake-0.18.5-1boelLdAnakJTib1YXjM5c:Development.Shake.Forward
* Raised the exception:
user error (2013601.md:5:64:
  |
5 | - [Some link](http://example.com/articles?include=author&fields[articles]=title)
  |                                                                ^
unexpected '['
expecting '#', '%', '&', '+', '/', ':', '=', '?', '@', end of URI, sub-delimiter, or unreserved character
```

Looks like the parser for links can't handle `[]` inside URLs? https://jsonapi.org/examples/ shows more examples (for in unit tests)

**Comment by srid** [comment]
It fails because the URI is invalid per RFC 3986 which [disallows square brackets](https://stackoverflow.com/a/1016737/55246) here.

neuron uses [mmark](https://github.com/mmark-md/mmark) to parse Markdown, which uses [modern-uri](http://hackage.haskell.org/package/modern-uri) to parse URIs.

We could file a issue in mmark requesting it to be more lenient. As a workaround try replacing `[` in the URL with `%5B`.

**Comment by luc-tielen** [comment]
I ended up replacing the link by a simpler 1 without `[` and `]` to fix it for now.

**Comment by srid** [comment]
Documented markdown limitations in 409a5a0.

**Comment by srid** [comment]
This is now fixed in `master`, with the move to Pandoc AST.

**Comment by luc-tielen** [comment]
Awesome! 🚀
