### ISSUE TITLE
We still spend time to traverse "ignored" directory/file while generating site

### ISSUE THREAD

**Issue by TheKK** [srid/neuron#607]
Currently implementation is like

https://github.com/srid/neuron/blob/49a4beb4c41400034ff4491c7e277a31cbb563c5/src/Neuron/Reactor/Build.hs#L235 

the filtering is after the `buildDirTree`.

In my case this makes generating site becomes **very** slow, since I'm using `nix direnv` and `neuron` still tries to parse `.direnv` which contains all the source of nix input.

I think the real issue is from https://github.com/obsidiansystems/directory-contents, which has issue with the `DirTree a` type. The representation is quite inefficient since it use `String/FilePath`. The experiment with my **quite small** blog project to change `String` to `Data.Text` shows that the heap usage is reduced from 8 Mib to 5 Mib. I'll open an issue there to discuss this issue.

**Comment by srid** [comment]
We use the directory-tree package only because it makes it simpler to create something like the `dirtree` plugin. But maybe that decision wasn't perfect. 

In retrospect `System.FilePattern.Directory` (from [filepattern](https://hackage.haskell.org/package/filepattern-0.1.2/docs/System-FilePattern-Directory.html)) would have been simpler choice, with custom code to build the tree from a list of files.

I should keep that in mind for https://github.com/srid/ema/issues/22

**Comment by srid** [comment]
FTR, Emanote avoids this library and uses `filepattern` directly. It's also got an innotative 'union mount' system for O(1) update,

https://github.com/srid/emanote/blob/master/src/Emanote/Source/Mount.hs

Closing per https://neuron.zettel.page/next
