### ISSUE TITLE
Standardize on zettel ID scheme

### ISSUE THREAD

**Issue by srid** [srid/neuron#70]
The general expectation so far is that the IDs are of [a specific format](https://neuron.srid.ca/2011403.html), although the app is pretty lenient ("index.md" for example works).

Some users, like @Nadrieril from #60, use a different ID scheme. 

One of the ideas in #59 is to support short and simple links like `<2011502>` (instead of the current `[2011502](z:/)`). Knowing what to expect ahead is necessary to properly parse links.

Should the next version of neuron:

- allow only numeric IDs like `2011502`?
- allow custom alphanumeric IDs like `20dtbvs` ([cf](https://old.reddit.com/r/Zettelkasten/comments/fa09zw/shorter_zettel_ids/fmhi8ky/))

I suppose a third option is to strongly recommend numeric IDs - but fail gracefully where users use alphanumeric IDs. For example, zquery's `theme=withDate` argument should render using the default theme, and render a warning in the HTML when the IDs are not date encoded numeric IDs. This inequality would have to be represented at the type level:

```haskell
data ZettelID 
  = DateID Day -- Numeric
  | CustomID Text -- Alpha numeric
```

**Comment by Nadrieril** [comment]
As mentioned, I'm in favor of supporting custom ids because that's what I use. The third option is good enough for me.
A different argument for arbitrary ids would be to be compatible with imports from other sources. I'm thinking specifically Zotero or similar software. The idea would be that I import each reference as a zettel; that means I can use the same id in my zettels and my LaTeX documents, and I get backlinks for each reference too.

**Comment by srid** [comment]
Hmm, I'm not keen on supporting importing from other software. But just out of curiosity, what is their ID formats like (if not of alphanumeric letters)?

**Comment by Nadrieril** [comment]
I didn't mean include such support in neuron, but just leave it possible if I want to write a script that does it.
Zotero (and bibtex) support arbitrary ids, but by default they're alphanumeric and look something like authorTitleOfPaper2020

**Comment by srid** [comment]
https://neuron.srid.ca/2011403.html
